name: Publish Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Generate a Release Package
      run: zip -r sample-website-${GITHUB_REF}.zip . -x 'LICENSE' -x 'README.md' -x 'Readme.txt' -x 'changelog.txt' -x '.github'
